{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.existingClaim }}
# skipped since existingClaim is set
{{ else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "unms.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{ end }}
{{ end }}
