apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "unms.fullname" . }}
  labels:
{{ include "unms.labels" . | indent 4 }}
spec:
  replicas: 1
  serviceName: "unms"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "unms.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "unms.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- if .Values.service.dashboard.http.enabled }}
            - name: http
              containerPort: 80
              protocol: TCP
            {{- end }}
            {{- if .Values.service.dashboard.https.enabled }}
            - name: https
              containerPort: 443
              protocol: TCP
            {{- end }}
            {{- if .Values.service.netflow.enabled }}
            - name: netflow
              containerPort: 2055
              protocol: UDP
            {{- end }}
          {{- if .Values.deployment.startupProbe }}
          startupProbe:
            {{- toYaml .Values.deployment.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.readinessProbe}}
          readinessProbe:
            {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.env }}
          env:
            {{- toYaml .Values.deployment.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- if .Values.deployment.persistence.enabled }}
          volumeMounts:
          - mountPath: /config
            name: data
          {{- end }}
      {{- if .Values.deployment.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
        {{- if .Values.deployment.persistence.existingClaim }}
          claimName: {{ .Values.deployment.persistence.existingClaim}}
        {{ else }}
          claimName: {{ include "unms.fullname" . }}
        {{- end }}
      {{ end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
